### ISSUE TITLE
can you please advise how to build it?

### ISSUE THREAD

**Issue by benja95** [freak07/Kirisakura_Raviole#1]
I'm trying to learn about this new GKI and trying to build it within google env,
but I guess that I'm doing it wrong since that compile fail (I'm running "BUILD_KERNEL=1 ./build_slider")

can you please assist?

thanks,

**Comment by freak07** [comment]
I invoke the build with 
`./build/build_abi.sh --update`

**Comment by Epikest** [comment]
> I invoke the build with `./build/build_abi.sh --update`

where did you get `./build/build_abi.sh`? i don't see it in the repo
